### ISSUE TITLE
Permisos de usuario

### ISSUE THREAD

**Issue by quommit** [siose-innova/siose-splitter#2]
@benizar  
Creo que en este repo tanto Pepe como yo tenemos permiso de lectura únicamente. Todos los miembros de la organización tenemos por defecto permiso de sólo lectura en todos los repos de los que no somos propietarios:  

![defaultpermissions](https://user-images.githubusercontent.com/3315149/39996460-db62cf2c-577f-11e8-851b-92a542460d7c.png)
  
No lo he cambiado porque creo que por defecto eso es bueno para evitar accidentes. ¿Nos puedes dar permiso de escritura  en el repo `siose-innova/siose-splitter`?

**Comment by benizar** [comment]
@quommit creo que ya está. ¿Me lo puedes confirmar?

**Comment by quommit** [comment]
Listo, muchas gracias! :)
